services:
    service-pg:
        image: bitnami/postgresql
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USERNAME=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=connectNLW
    service-redis:
        image: bitnami/redis
        ports:
            - "6379:6379"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes